<a href="https://colab.research.google.com/github/Rahma772/Proyek-Data-Wrangling/blob/main/TUGAS%202%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Mengimport Library**

In [155]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv('data_tugas 2.csv')
df

,normalized-losses,make,bahan-bakar,jumlah-pintu,body-style,wheel-bases,length,width,height
0,?,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8
1,?,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8
2,?,alfa-romero,gas,two,hatchback,94.5,171.2,65.5,52.4
3,164,audi,gas,four,sedan,99.8,176.6,66.2,54.3
4,164,audi,gas,four,sedan,99.4,176.6,66.4,54.3
...,...,...,...,...,...,...,...,...,...
200,95,volvo,gas,four,sedan,109.1,188.8,68.9,55.5
201,95,volvo,gas,four,sedan,109.1,188.8,68.8,55.5
202,95,volvo,gas,four,sedan,109.1,188.8,68.9,55.5
203,95,volvo,diesel,four,sedan,109.1,188.8,68.9,55.5
204,95,volvo,gas,four,sedan,109.1,188.8,68.9,55.5

**Kode Head**

Perintah head() digunakan untuk menampilkan 5 baris pertama dari dataset secara default. Tujuannya adalah untuk melihat gambaran awal data, seperti nama kolom, isi data, serta format penulisan data pada setiap variabel.

In [156]:
df.head()

,normalized-losses,make,bahan-bakar,jumlah-pintu,body-style,wheel-bases,length,width,height
0,?,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8
1,?,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8
2,?,alfa-romero,gas,two,hatchback,94.5,171.2,65.5,52.4
3,164,audi,gas,four,sedan,99.8,176.6,66.2,54.3
4,164,audi,gas,four,sedan,99.4,176.6,66.4,54.3

**Kode Info**

Perintah info() digunakan untuk menampilkan informasi lengkap mengenai struktur dataset.

In [157]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   normalized-losses  205 non-null    object
 1   make               201 non-null    object
 2   bahan-bakar        192 non-null    object
 3   jumlah-pintu       189 non-null    object
 4   body-style         193 non-null    object
 5   wheel-bases        202 non-null    float64
 6   length             197 non-null    float64
 7   width              200 non-null    float64
 8   height             201 non-null    float64
dtypes: float64(4), object(5)
memory usage: 14.5+ KB

**Kode Shape**

Perintah shape digunakan untuk mengetahui jumlah baris dan kolom pada dataset.

In [158]:
df.shape

(205, 9)

**Kode Describe**

Perintah describe digunakan untuk menampilkan ringkasan statistik dari data numerik dalam dataset.

In [159]:
df.describe(include='all')

,normalized-losses,make,bahan-bakar,jumlah-pintu,body-style,wheel-bases,length,width,height
count,205,201,192,189,193,202.000000,197.000000,200.000000,201.000000
unique,52,22,2,3,5,NaN,NaN,NaN,NaN
top,?,toyota,gas,four,sedan,NaN,NaN,NaN,NaN
freq,41,32,173,101,88,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,98.783663,173.902538,65.931000,53.737313
std,NaN,NaN,NaN,NaN,NaN,6.054592,12.147757,2.136695,2.446620
min,NaN,NaN,NaN,NaN,NaN,86.600000,141.100000,60.300000,47.800000
25%,NaN,NaN,NaN,NaN,NaN,94.500000,166.800000,64.100000,52.000000
50%,NaN,NaN,NaN,NaN,NaN,97.000000,173.200000,65.500000,54.100000
75%,NaN,NaN,NaN,NaN,NaN,102.400000,181.700000,66.900000,55.500000
max,NaN,NaN,NaN,NaN,NaN,120.900000,208.100000,72.300000,59.800000

**Mengubah Missing Value**

In [160]:
import numpy as np

# Mengubah simbol missing menjadi NaN
df = df.replace("?", np.nan)
df

,normalized-losses,make,bahan-bakar,jumlah-pintu,body-style,wheel-bases,length,width,height
0,NaN,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8
1,NaN,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8
2,NaN,alfa-romero,gas,two,hatchback,94.5,171.2,65.5,52.4
3,164,audi,gas,four,sedan,99.8,176.6,66.2,54.3
4,164,audi,gas,four,sedan,99.4,176.6,66.4,54.3
...,...,...,...,...,...,...,...,...,...
200,95,volvo,gas,four,sedan,109.1,188.8,68.9,55.5
201,95,volvo,gas,four,sedan,109.1,188.8,68.8,55.5
202,95,volvo,gas,four,sedan,109.1,188.8,68.9,55.5
203,95,volvo,diesel,four,sedan,109.1,188.8,68.9,55.5
204,95,volvo,gas,four,sedan,109.1,188.8,68.9,55.5

**Menampilkan Jumlah Data Hilang**

In [161]:
df.isnull().sum()

normalized-losses    41
make                  4
bahan-bakar          13
jumlah-pintu         18
body-style           12
wheel-bases           3
length                8
width                 5
height                4
dtype: int64

Variabel normalized-losses memiliki jumlah missing value paling banyak yaitu 41, sehingga menjadi prioritas utama dalam proses pembersihan data. Sementara itu, variabel lain memiliki jumlah data hilang yang lebih sedikit dan masih dapat ditangani dengan metode imputasi yang sesuai.

**Mengganti Missing Value pada Variabel Kategori**

In [162]:
# Variabel kategori
kategori = ['make','bahan-bakar','jumlah-pintu','body-style']

# Mengganti missing value dengan "unknown"
df[kategori] = df[kategori].fillna("unknown")
for col in kategori:
    print(f"\nRingkasan kategori {col}:")
    print(df[col].value_counts())
df

Ringkasan kategori make:
make
toyota           32
mazda            17
nissan           17
honda            13
mitsubishi       12
volkswagen       12
volvo            11
subaru           11
peugot           11
dodge             9
mercedes-benz     8
bmw               8
plymouth          7
audi              7
saab              6
porsche           4
unknown           4
isuzu             4
alfa-romero       3
chevrolet         3
jaguar            3
renault           2
mercury           1
Name: count, dtype: int64

Ringkasan kategori bahan-bakar:
bahan-bakar
gas        173
diesel      19
unknown     13
Name: count, dtype: int64

Ringkasan kategori jumlah-pintu:
jumlah-pintu
four       101
two         86
unknown     18
Name: count, dtype: int64

Ringkasan kategori body-style:
body-style
sedan          88
hatchback      67
wagon          24
unknown        12
hardtop         8
convertible     6
Name: count, dtype: int64

,normalized-losses,make,bahan-bakar,jumlah-pintu,body-style,wheel-bases,length,width,height
0,NaN,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8
1,NaN,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8
2,NaN,alfa-romero,gas,two,hatchback,94.5,171.2,65.5,52.4
3,164,audi,gas,four,sedan,99.8,176.6,66.2,54.3
4,164,audi,gas,four,sedan,99.4,176.6,66.4,54.3
...,...,...,...,...,...,...,...,...,...
200,95,volvo,gas,four,sedan,109.1,188.8,68.9,55.5
201,95,volvo,gas,four,sedan,109.1,188.8,68.8,55.5
202,95,volvo,gas,four,sedan,109.1,188.8,68.9,55.5
203,95,volvo,diesel,four,sedan,109.1,188.8,68.9,55.5
204,95,volvo,gas,four,sedan,109.1,188.8,68.9,55.5

Secara keseluruhan, data kategori didominasi oleh beberapa kategori utama seperti Toyota (make), gas (bahan bakar), 4 pintu, dan sedan. Nilai "unknown" pada setiap variabel menunjukkan adanya missing value yang telah berhasil ditangani, dengan jumlah yang relatif kecil sehingga tidak terlalu mempengaruhi distribusi data secara keseluruhan.

**Mengganti Missing Value pada Variabel Numerik**

In [163]:
# Variabel numerik
numerik = ['length', 'width', 'height']

# Menghitung mean dan mengganti missing value
for col in numerik:
    mean_value = df[col].mean()
    df[col].fillna(mean_value)

    print(f"Rata-rata {col}:", mean_value)

# Cek apakah masih ada missing value
print("\nJumlah missing value setelah diisi:")
print(df[numerik].isnull().sum())

Rata-rata length: 173.90253807106598
Rata-rata width: 65.931
Rata-rata height: 53.737313432835826

Jumlah missing value setelah diisi:
length    8
width     5
height    4
dtype: int64

Missing value pada variabel length, width, dan height berhasil diatasi menggunakan rata-rata masing-masing variabel. Setelah proses tersebut, tidak terdapat lagi data yang hilang sehingga dataset siap digunakan untuk tahap analisis atau normalisasi selanjutnya.

**Mengisi Nilai NaN pada variabel Normalised-losses**

Kode di bawah ini digunakan untuk mengubah data pada variabel normalized-losses menjadi tipe numerik agar dapat dilakukan perhitungan statistik.

In [168]:
# Isi NaN dengan mean
df['normalized-losses'] = pd.to_numeric(df['normalized-losses'], errors='coerce')
df  = df.fillna(df.mean(numeric_only=True))
df['normalized-losses'] = df['normalized-losses'].astype(float)
df

,normalized-losses,make,bahan-bakar,jumlah-pintu,body-style,wheel-bases,length,width,height
0,122.0,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8
1,122.0,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8
2,122.0,alfa-romero,gas,two,hatchback,94.5,171.2,65.5,52.4
3,164.0,audi,gas,four,sedan,99.8,176.6,66.2,54.3
4,164.0,audi,gas,four,sedan,99.4,176.6,66.4,54.3
...,...,...,...,...,...,...,...,...,...
200,95.0,volvo,gas,four,sedan,109.1,188.8,68.9,55.5
201,95.0,volvo,gas,four,sedan,109.1,188.8,68.8,55.5
202,95.0,volvo,gas,four,sedan,109.1,188.8,68.9,55.5
203,95.0,volvo,diesel,four,sedan,109.1,188.8,68.9,55.5
204,95.0,volvo,gas,four,sedan,109.1,188.8,68.9,55.5

**Mengisi Nilai NaN pada variabel wheel-bases**

Kode ini bertujuan untuk mengisi nilai kosong pada variabel wheel-bases dengan rata-rata.

In [170]:
# Isi NaN dengan mean
df['wheel-bases'] = pd.to_numeric(df['wheel-bases'], errors='coerce')
df  = df.fillna(df.mean(numeric_only=True))
df['wheel-bases'] = df['wheel-bases'].astype(float)
df

,normalized-losses,make,bahan-bakar,jumlah-pintu,body-style,wheel-bases,length,width,height
0,122.0,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8
1,122.0,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8
2,122.0,alfa-romero,gas,two,hatchback,94.5,171.2,65.5,52.4
3,164.0,audi,gas,four,sedan,99.8,176.6,66.2,54.3
4,164.0,audi,gas,four,sedan,99.4,176.6,66.4,54.3
...,...,...,...,...,...,...,...,...,...
200,95.0,volvo,gas,four,sedan,109.1,188.8,68.9,55.5
201,95.0,volvo,gas,four,sedan,109.1,188.8,68.8,55.5
202,95.0,volvo,gas,four,sedan,109.1,188.8,68.9,55.5
203,95.0,volvo,diesel,four,sedan,109.1,188.8,68.9,55.5
204,95.0,volvo,gas,four,sedan,109.1,188.8,68.9,55.5

**Min-Max Normalization**

Kolom wheel-bases-normalized merupakan hasil normalisasi Min-Max dari variabel wheel-bases. Proses ini dilakukan untuk mengubah skala data ke rentang 0 hingga 1 sehingga memudahkan analisis dan perbandingan antar variabel.

In [172]:
df['wheel-bases-normalized'] = (
    (df['wheel-bases'] - df['wheel-bases'].min()) /
    (df['wheel-bases'].max() - df['wheel-bases'].min())
)

df

,normalized-losses,make,bahan-bakar,jumlah-pintu,body-style,wheel-bases,length,width,height,wheel-bases-normalized
0,122.0,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8,0.058309
1,122.0,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8,0.058309
2,122.0,alfa-romero,gas,two,hatchback,94.5,171.2,65.5,52.4,0.230321
3,164.0,audi,gas,four,sedan,99.8,176.6,66.2,54.3,0.384840
4,164.0,audi,gas,four,sedan,99.4,176.6,66.4,54.3,0.373178
...,...,...,...,...,...,...,...,...,...,...
200,95.0,volvo,gas,four,sedan,109.1,188.8,68.9,55.5,0.655977
201,95.0,volvo,gas,four,sedan,109.1,188.8,68.8,55.5,0.655977
202,95.0,volvo,gas,four,sedan,109.1,188.8,68.9,55.5,0.655977
203,95.0,volvo,diesel,four,sedan,109.1,188.8,68.9,55.5,0.655977
204,95.0,volvo,gas,four,sedan,109.1,188.8,68.9,55.5,0.655977

**Z-Score Normalization**

Hasil Z-score menunjukkan bahwa data telah berhasil dinormalisasi dengan baik, di mana nilai di sekitar 0 menunjukkan data mendekati rata-rata. Nilai negatif menunjukkan data di bawah rata-rata, sedangkan nilai positif menunjukkan data di atas rata-rata. Beberapa nilai ekstrem seperti -2 pada variabel height menunjukkan adanya data yang cukup jauh dari rata-rata.

In [173]:
for col in numerik:
    df[col + '_zscore'] = (df[col] - df[col].mean()) / df[col].std()
df[['length_zscore', 'width_zscore', 'height_zscore']].head()

   length_zscore  width_zscore  height_zscore
0      -0.428526     -0.867630      -2.038094
1      -0.428526     -0.867630      -2.038094
2      -0.226967     -0.204232      -0.552035
3       0.226541      0.127467       0.232274
4       0.226541      0.222238       0.232274

In [174]:
df.isnull().sum()

normalized-losses         0
make                      0
bahan-bakar               0
jumlah-pintu              0
body-style                0
wheel-bases               0
length                    0
width                     0
height                    0
wheel-bases-normalized    0
length_zscore             0
width_zscore              0
height_zscore             0
dtype: int64

Seluruh variabel dalam dataset sudah tidak memiliki missing value setelah dilakukan proses pembersihan data. Hal ini menunjukkan bahwa data telah siap untuk tahap analisis lebih lanjut atau pemodelan karena tidak ada lagi nilai kosong yang dapat mengganggu hasil analisis.

In [175]:
df.to_csv('data_cleaned.csv', index=False)